---
- include_tasks: upgrade_debian.yml
  when: ansible_os_family == "Debian"
  tags: upgrade

- include_tasks: upgrade_gem.yml
  tags: upgrade
  when: upgrade_gem

- include_tasks: upgrade_npm.yml
  tags: upgrade
  when: upgrade_npm
