---
- name: Check if npm is installed
  command: 'which npm'
  register: which_npm
  changed_when: False
  failed_when: False

- name: Update npm
  command: 'npm update -g'
  when: "which_npm.stdout and 'not found' not in which_npm.stdout"
